name: deploy docker
on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: deploy through docker compose up
        uses: docker/setup-compose-action@v2
        with:
          version: latest
      - name: Run the docker compose
        run: docker compose up --build -d
