name: Portfolio Workflow

on:
    push:
        branches:
            - main
    workflow_dispatch: 
permissions:
  contents: read
  pages: write
  id-token: write            
jobs:
    deploy:
        environment:
            ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true
            FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              
            - name: setup Gihub pages
              uses: actions/configure-pages@v4
              
            - name: Upload to GitHub Pages
              uses: actions/upload-pages-artifact@v4
              with:
                path: "."
                
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
